name: Profile Summary Cards

on:
  schedule:
    - cron: "0 2 * * *"    # ejecuta cada día a las 02:00 UTC
  workflow_dispatch:       # permite lanzarlo a mano desde Actions

# Necesario para que el action pueda commitear las imágenes generadas
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Genera y commitea las tarjetas en profile-summary-card-output/<theme>/
      - name: Generate GitHub Summary Cards (include private repos)
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Token automático para hacer commit en el repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tu PAT (fine-grained o classic) con permisos de lectura
          ACCESS_TOKEN: ${{ secrets.ACCESSTOKEN }}
        with:
          USERNAME: MariaOcete
          THEME: 2077
          # EXCLUDE: "Jupyter Notebook"   # opcional, para limpiar "Top Languages"
