name: Profile Summary Cards

on:
  schedule:
    - cron: '0 2 * * *'   # genera las tarjetas a diario
  workflow_dispatch:       # te permite ejecutarlo a mano

permissions:
  contents: write          # necesario para commitear las imágenes generadas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Genera y commitea las tarjetas en profile-summary-card-output/<theme>/
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Si quieres contar repos privados, crea un PAT y guárdalo como ACCESS_TOKEN.
          # Si no, puedes empezar con el token por defecto del repo:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          USERNAME: MariaOcete
          THEME: 2077   # puedes cambiar a 'tokyonight', 'dracula', 'github_dark', etc.
