name: Profile Summary Cards

on:
  schedule:
    - cron: '0 2 * * *'   # todos los días 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write         # para commitear las imágenes generadas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Opcional) Comprobar que el PAT puede leer repos privados
      - name: Sanity check private repos
        env:
          GH_TOKEN: ${{ secrets.ACCESSTOKEN }}   # tu PAT guardado como ACCESSTOKEN
        run: |
          echo "Private repos count:"
          gh repo list ${GITHUB_REPOSITORY%%/*} --private --json name --jq 'length' || true

      - name: Generate GitHub Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # TOKEN para hacer el commit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PAT para que cuente privados (tu secret ACCESSTOKEN)
          ACCESS_TOKEN: ${{ secrets.ACCESSTOKEN }}
        with:
          USERNAME: MariaOcete
          # Puedes usar además:
          # EXCLUDE: "Jupyter Notebook"   # para “limpiar” Top Languages
          # AUTO_PUSH: "true"             # por defecto ya hace push
          # BRANCH_NAME: "main"           # si tu default branch no es main
