name: Profile Summary Cards

on:
  schedule:
    - cron: "0 2 * * *"   # todos los días a las 02:00 UTC
  workflow_dispatch:       # permite lanzarlo a mano

# Necesario para que el action pueda commitear las imágenes generadas
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Opcional) Comprobar que el PAT ve repos privados (sin warnings)
      - name: Sanity check private repos
        env:
          GH_TOKEN: ${{ secrets.ACCESSTOKEN }}   # tu PAT guardado como ACCESSTOKEN
        run: |
          echo "Private repos count:"
          gh repo list ${{ github.repository_owner }} --visibility=private --json name -q 'length'

      # Genera y commitea las tarjetas en profile-summary-card-output/<theme>/
      - name: Generate GitHub Summary Cards (include private repos)
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Token automático para hacer commit en el repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tu PAT (fine-grained o classic) con permisos de lectura
          ACCESS_TOKEN: ${{ secrets.ACCESSTOKEN }}
        with:
          USERNAME: MariaOcete
          BRANCH_NAME: main
          EXCLUDE: "HTML,CSS"   # evita que HTML/CSS tapen los demás lenguajes
          UTC_OFFSET: "+1"      # opcional: tu zona (Andalucía = UTC+1 en horario de verano)
          THEME: 2077

